// Code generated by ent, DO NOT EDIT.

package ico

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/rs/xid"
)

const (
	// Label holds the string label denoting the ico type in the database.
	Label = "ico"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldRoundID holds the string denoting the round_id field in the database.
	FieldRoundID = "round_id"
	// FieldRoundName holds the string denoting the round_name field in the database.
	FieldRoundName = "round_name"
	// FieldPrice holds the string denoting the price field in the database.
	FieldPrice = "price"
	// FieldNumToken holds the string denoting the num_token field in the database.
	FieldNumToken = "num_token"
	// FieldNumSub holds the string denoting the num_sub field in the database.
	FieldNumSub = "num_sub"
	// FieldPriceGap holds the string denoting the price_gap field in the database.
	FieldPriceGap = "price_gap"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// Table holds the table name of the ico in the database.
	Table = "icos"
)

// Columns holds all SQL columns for ico fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldRoundID,
	FieldRoundName,
	FieldPrice,
	FieldNumToken,
	FieldNumSub,
	FieldPriceGap,
	FieldEndedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() xid.ID
)

// OrderOption defines the ordering options for the Ico queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByRoundID orders the results by the round_id field.
func ByRoundID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoundID, opts...).ToFunc()
}

// ByRoundName orders the results by the round_name field.
func ByRoundName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRoundName, opts...).ToFunc()
}

// ByPrice orders the results by the price field.
func ByPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrice, opts...).ToFunc()
}

// ByNumToken orders the results by the num_token field.
func ByNumToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumToken, opts...).ToFunc()
}

// ByNumSub orders the results by the num_sub field.
func ByNumSub(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNumSub, opts...).ToFunc()
}

// ByPriceGap orders the results by the price_gap field.
func ByPriceGap(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriceGap, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}
