// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/indikay/wallet-service/ent/icocoupon"
	"github.com/indikay/wallet-service/ent/predicate"
)

// IcoCouponDelete is the builder for deleting a IcoCoupon entity.
type IcoCouponDelete struct {
	config
	hooks    []Hook
	mutation *IcoCouponMutation
}

// Where appends a list predicates to the IcoCouponDelete builder.
func (icd *IcoCouponDelete) Where(ps ...predicate.IcoCoupon) *IcoCouponDelete {
	icd.mutation.Where(ps...)
	return icd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (icd *IcoCouponDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, icd.sqlExec, icd.mutation, icd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (icd *IcoCouponDelete) ExecX(ctx context.Context) int {
	n, err := icd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (icd *IcoCouponDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(icocoupon.Table, sqlgraph.NewFieldSpec(icocoupon.FieldID, field.TypeString))
	if ps := icd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, icd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	icd.mutation.done = true
	return affected, err
}

// IcoCouponDeleteOne is the builder for deleting a single IcoCoupon entity.
type IcoCouponDeleteOne struct {
	icd *IcoCouponDelete
}

// Where appends a list predicates to the IcoCouponDelete builder.
func (icdo *IcoCouponDeleteOne) Where(ps ...predicate.IcoCoupon) *IcoCouponDeleteOne {
	icdo.icd.mutation.Where(ps...)
	return icdo
}

// Exec executes the deletion query.
func (icdo *IcoCouponDeleteOne) Exec(ctx context.Context) error {
	n, err := icdo.icd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{icocoupon.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (icdo *IcoCouponDeleteOne) ExecX(ctx context.Context) {
	if err := icdo.Exec(ctx); err != nil {
		panic(err)
	}
}
