// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/indikay/wallet-service/ent/icocoupon"
	"github.com/indikay/wallet-service/ent/predicate"
	"github.com/rs/xid"
)

// IcoCouponQuery is the builder for querying IcoCoupon entities.
type IcoCouponQuery struct {
	config
	ctx        *QueryContext
	order      []icocoupon.OrderOption
	inters     []Interceptor
	predicates []predicate.IcoCoupon
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IcoCouponQuery builder.
func (icq *IcoCouponQuery) Where(ps ...predicate.IcoCoupon) *IcoCouponQuery {
	icq.predicates = append(icq.predicates, ps...)
	return icq
}

// Limit the number of records to be returned by this query.
func (icq *IcoCouponQuery) Limit(limit int) *IcoCouponQuery {
	icq.ctx.Limit = &limit
	return icq
}

// Offset to start from.
func (icq *IcoCouponQuery) Offset(offset int) *IcoCouponQuery {
	icq.ctx.Offset = &offset
	return icq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (icq *IcoCouponQuery) Unique(unique bool) *IcoCouponQuery {
	icq.ctx.Unique = &unique
	return icq
}

// Order specifies how the records should be ordered.
func (icq *IcoCouponQuery) Order(o ...icocoupon.OrderOption) *IcoCouponQuery {
	icq.order = append(icq.order, o...)
	return icq
}

// First returns the first IcoCoupon entity from the query.
// Returns a *NotFoundError when no IcoCoupon was found.
func (icq *IcoCouponQuery) First(ctx context.Context) (*IcoCoupon, error) {
	nodes, err := icq.Limit(1).All(setContextOp(ctx, icq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{icocoupon.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (icq *IcoCouponQuery) FirstX(ctx context.Context) *IcoCoupon {
	node, err := icq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IcoCoupon ID from the query.
// Returns a *NotFoundError when no IcoCoupon ID was found.
func (icq *IcoCouponQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = icq.Limit(1).IDs(setContextOp(ctx, icq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{icocoupon.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (icq *IcoCouponQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := icq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IcoCoupon entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IcoCoupon entity is found.
// Returns a *NotFoundError when no IcoCoupon entities are found.
func (icq *IcoCouponQuery) Only(ctx context.Context) (*IcoCoupon, error) {
	nodes, err := icq.Limit(2).All(setContextOp(ctx, icq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{icocoupon.Label}
	default:
		return nil, &NotSingularError{icocoupon.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (icq *IcoCouponQuery) OnlyX(ctx context.Context) *IcoCoupon {
	node, err := icq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IcoCoupon ID in the query.
// Returns a *NotSingularError when more than one IcoCoupon ID is found.
// Returns a *NotFoundError when no entities are found.
func (icq *IcoCouponQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = icq.Limit(2).IDs(setContextOp(ctx, icq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{icocoupon.Label}
	default:
		err = &NotSingularError{icocoupon.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (icq *IcoCouponQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := icq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IcoCoupons.
func (icq *IcoCouponQuery) All(ctx context.Context) ([]*IcoCoupon, error) {
	ctx = setContextOp(ctx, icq.ctx, "All")
	if err := icq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IcoCoupon, *IcoCouponQuery]()
	return withInterceptors[[]*IcoCoupon](ctx, icq, qr, icq.inters)
}

// AllX is like All, but panics if an error occurs.
func (icq *IcoCouponQuery) AllX(ctx context.Context) []*IcoCoupon {
	nodes, err := icq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IcoCoupon IDs.
func (icq *IcoCouponQuery) IDs(ctx context.Context) (ids []xid.ID, err error) {
	if icq.ctx.Unique == nil && icq.path != nil {
		icq.Unique(true)
	}
	ctx = setContextOp(ctx, icq.ctx, "IDs")
	if err = icq.Select(icocoupon.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (icq *IcoCouponQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := icq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (icq *IcoCouponQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, icq.ctx, "Count")
	if err := icq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, icq, querierCount[*IcoCouponQuery](), icq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (icq *IcoCouponQuery) CountX(ctx context.Context) int {
	count, err := icq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (icq *IcoCouponQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, icq.ctx, "Exist")
	switch _, err := icq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (icq *IcoCouponQuery) ExistX(ctx context.Context) bool {
	exist, err := icq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IcoCouponQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (icq *IcoCouponQuery) Clone() *IcoCouponQuery {
	if icq == nil {
		return nil
	}
	return &IcoCouponQuery{
		config:     icq.config,
		ctx:        icq.ctx.Clone(),
		order:      append([]icocoupon.OrderOption{}, icq.order...),
		inters:     append([]Interceptor{}, icq.inters...),
		predicates: append([]predicate.IcoCoupon{}, icq.predicates...),
		// clone intermediate query.
		sql:  icq.sql.Clone(),
		path: icq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IcoCoupon.Query().
//		GroupBy(icocoupon.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (icq *IcoCouponQuery) GroupBy(field string, fields ...string) *IcoCouponGroupBy {
	icq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IcoCouponGroupBy{build: icq}
	grbuild.flds = &icq.ctx.Fields
	grbuild.label = icocoupon.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.IcoCoupon.Query().
//		Select(icocoupon.FieldCreatedAt).
//		Scan(ctx, &v)
func (icq *IcoCouponQuery) Select(fields ...string) *IcoCouponSelect {
	icq.ctx.Fields = append(icq.ctx.Fields, fields...)
	sbuild := &IcoCouponSelect{IcoCouponQuery: icq}
	sbuild.label = icocoupon.Label
	sbuild.flds, sbuild.scan = &icq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IcoCouponSelect configured with the given aggregations.
func (icq *IcoCouponQuery) Aggregate(fns ...AggregateFunc) *IcoCouponSelect {
	return icq.Select().Aggregate(fns...)
}

func (icq *IcoCouponQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range icq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, icq); err != nil {
				return err
			}
		}
	}
	for _, f := range icq.ctx.Fields {
		if !icocoupon.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if icq.path != nil {
		prev, err := icq.path(ctx)
		if err != nil {
			return err
		}
		icq.sql = prev
	}
	return nil
}

func (icq *IcoCouponQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IcoCoupon, error) {
	var (
		nodes = []*IcoCoupon{}
		_spec = icq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IcoCoupon).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IcoCoupon{config: icq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(icq.modifiers) > 0 {
		_spec.Modifiers = icq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, icq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (icq *IcoCouponQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := icq.querySpec()
	if len(icq.modifiers) > 0 {
		_spec.Modifiers = icq.modifiers
	}
	_spec.Node.Columns = icq.ctx.Fields
	if len(icq.ctx.Fields) > 0 {
		_spec.Unique = icq.ctx.Unique != nil && *icq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, icq.driver, _spec)
}

func (icq *IcoCouponQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(icocoupon.Table, icocoupon.Columns, sqlgraph.NewFieldSpec(icocoupon.FieldID, field.TypeString))
	_spec.From = icq.sql
	if unique := icq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if icq.path != nil {
		_spec.Unique = true
	}
	if fields := icq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, icocoupon.FieldID)
		for i := range fields {
			if fields[i] != icocoupon.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := icq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := icq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := icq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := icq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (icq *IcoCouponQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(icq.driver.Dialect())
	t1 := builder.Table(icocoupon.Table)
	columns := icq.ctx.Fields
	if len(columns) == 0 {
		columns = icocoupon.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if icq.sql != nil {
		selector = icq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if icq.ctx.Unique != nil && *icq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range icq.modifiers {
		m(selector)
	}
	for _, p := range icq.predicates {
		p(selector)
	}
	for _, p := range icq.order {
		p(selector)
	}
	if offset := icq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := icq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (icq *IcoCouponQuery) Modify(modifiers ...func(s *sql.Selector)) *IcoCouponSelect {
	icq.modifiers = append(icq.modifiers, modifiers...)
	return icq.Select()
}

// IcoCouponGroupBy is the group-by builder for IcoCoupon entities.
type IcoCouponGroupBy struct {
	selector
	build *IcoCouponQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (icgb *IcoCouponGroupBy) Aggregate(fns ...AggregateFunc) *IcoCouponGroupBy {
	icgb.fns = append(icgb.fns, fns...)
	return icgb
}

// Scan applies the selector query and scans the result into the given value.
func (icgb *IcoCouponGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, icgb.build.ctx, "GroupBy")
	if err := icgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IcoCouponQuery, *IcoCouponGroupBy](ctx, icgb.build, icgb, icgb.build.inters, v)
}

func (icgb *IcoCouponGroupBy) sqlScan(ctx context.Context, root *IcoCouponQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(icgb.fns))
	for _, fn := range icgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*icgb.flds)+len(icgb.fns))
		for _, f := range *icgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*icgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := icgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IcoCouponSelect is the builder for selecting fields of IcoCoupon entities.
type IcoCouponSelect struct {
	*IcoCouponQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ics *IcoCouponSelect) Aggregate(fns ...AggregateFunc) *IcoCouponSelect {
	ics.fns = append(ics.fns, fns...)
	return ics
}

// Scan applies the selector query and scans the result into the given value.
func (ics *IcoCouponSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ics.ctx, "Select")
	if err := ics.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IcoCouponQuery, *IcoCouponSelect](ctx, ics.IcoCouponQuery, ics, ics.inters, v)
}

func (ics *IcoCouponSelect) sqlScan(ctx context.Context, root *IcoCouponQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ics.fns))
	for _, fn := range ics.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ics.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ics.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ics *IcoCouponSelect) Modify(modifiers ...func(s *sql.Selector)) *IcoCouponSelect {
	ics.modifiers = append(ics.modifiers, modifiers...)
	return ics
}
