// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/indikay/wallet-service/ent/icohistory"
	"github.com/indikay/wallet-service/ent/predicate"
	"github.com/rs/xid"
)

// IcoHistoryQuery is the builder for querying IcoHistory entities.
type IcoHistoryQuery struct {
	config
	ctx        *QueryContext
	order      []icohistory.OrderOption
	inters     []Interceptor
	predicates []predicate.IcoHistory
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IcoHistoryQuery builder.
func (ihq *IcoHistoryQuery) Where(ps ...predicate.IcoHistory) *IcoHistoryQuery {
	ihq.predicates = append(ihq.predicates, ps...)
	return ihq
}

// Limit the number of records to be returned by this query.
func (ihq *IcoHistoryQuery) Limit(limit int) *IcoHistoryQuery {
	ihq.ctx.Limit = &limit
	return ihq
}

// Offset to start from.
func (ihq *IcoHistoryQuery) Offset(offset int) *IcoHistoryQuery {
	ihq.ctx.Offset = &offset
	return ihq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ihq *IcoHistoryQuery) Unique(unique bool) *IcoHistoryQuery {
	ihq.ctx.Unique = &unique
	return ihq
}

// Order specifies how the records should be ordered.
func (ihq *IcoHistoryQuery) Order(o ...icohistory.OrderOption) *IcoHistoryQuery {
	ihq.order = append(ihq.order, o...)
	return ihq
}

// First returns the first IcoHistory entity from the query.
// Returns a *NotFoundError when no IcoHistory was found.
func (ihq *IcoHistoryQuery) First(ctx context.Context) (*IcoHistory, error) {
	nodes, err := ihq.Limit(1).All(setContextOp(ctx, ihq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{icohistory.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ihq *IcoHistoryQuery) FirstX(ctx context.Context) *IcoHistory {
	node, err := ihq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IcoHistory ID from the query.
// Returns a *NotFoundError when no IcoHistory ID was found.
func (ihq *IcoHistoryQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = ihq.Limit(1).IDs(setContextOp(ctx, ihq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{icohistory.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ihq *IcoHistoryQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := ihq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IcoHistory entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IcoHistory entity is found.
// Returns a *NotFoundError when no IcoHistory entities are found.
func (ihq *IcoHistoryQuery) Only(ctx context.Context) (*IcoHistory, error) {
	nodes, err := ihq.Limit(2).All(setContextOp(ctx, ihq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{icohistory.Label}
	default:
		return nil, &NotSingularError{icohistory.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ihq *IcoHistoryQuery) OnlyX(ctx context.Context) *IcoHistory {
	node, err := ihq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IcoHistory ID in the query.
// Returns a *NotSingularError when more than one IcoHistory ID is found.
// Returns a *NotFoundError when no entities are found.
func (ihq *IcoHistoryQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = ihq.Limit(2).IDs(setContextOp(ctx, ihq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{icohistory.Label}
	default:
		err = &NotSingularError{icohistory.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ihq *IcoHistoryQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := ihq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IcoHistories.
func (ihq *IcoHistoryQuery) All(ctx context.Context) ([]*IcoHistory, error) {
	ctx = setContextOp(ctx, ihq.ctx, "All")
	if err := ihq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IcoHistory, *IcoHistoryQuery]()
	return withInterceptors[[]*IcoHistory](ctx, ihq, qr, ihq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ihq *IcoHistoryQuery) AllX(ctx context.Context) []*IcoHistory {
	nodes, err := ihq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IcoHistory IDs.
func (ihq *IcoHistoryQuery) IDs(ctx context.Context) (ids []xid.ID, err error) {
	if ihq.ctx.Unique == nil && ihq.path != nil {
		ihq.Unique(true)
	}
	ctx = setContextOp(ctx, ihq.ctx, "IDs")
	if err = ihq.Select(icohistory.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ihq *IcoHistoryQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := ihq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ihq *IcoHistoryQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ihq.ctx, "Count")
	if err := ihq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ihq, querierCount[*IcoHistoryQuery](), ihq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ihq *IcoHistoryQuery) CountX(ctx context.Context) int {
	count, err := ihq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ihq *IcoHistoryQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ihq.ctx, "Exist")
	switch _, err := ihq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ihq *IcoHistoryQuery) ExistX(ctx context.Context) bool {
	exist, err := ihq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IcoHistoryQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ihq *IcoHistoryQuery) Clone() *IcoHistoryQuery {
	if ihq == nil {
		return nil
	}
	return &IcoHistoryQuery{
		config:     ihq.config,
		ctx:        ihq.ctx.Clone(),
		order:      append([]icohistory.OrderOption{}, ihq.order...),
		inters:     append([]Interceptor{}, ihq.inters...),
		predicates: append([]predicate.IcoHistory{}, ihq.predicates...),
		// clone intermediate query.
		sql:  ihq.sql.Clone(),
		path: ihq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IcoHistory.Query().
//		GroupBy(icohistory.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ihq *IcoHistoryQuery) GroupBy(field string, fields ...string) *IcoHistoryGroupBy {
	ihq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IcoHistoryGroupBy{build: ihq}
	grbuild.flds = &ihq.ctx.Fields
	grbuild.label = icohistory.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.IcoHistory.Query().
//		Select(icohistory.FieldCreatedAt).
//		Scan(ctx, &v)
func (ihq *IcoHistoryQuery) Select(fields ...string) *IcoHistorySelect {
	ihq.ctx.Fields = append(ihq.ctx.Fields, fields...)
	sbuild := &IcoHistorySelect{IcoHistoryQuery: ihq}
	sbuild.label = icohistory.Label
	sbuild.flds, sbuild.scan = &ihq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IcoHistorySelect configured with the given aggregations.
func (ihq *IcoHistoryQuery) Aggregate(fns ...AggregateFunc) *IcoHistorySelect {
	return ihq.Select().Aggregate(fns...)
}

func (ihq *IcoHistoryQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ihq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ihq); err != nil {
				return err
			}
		}
	}
	for _, f := range ihq.ctx.Fields {
		if !icohistory.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ihq.path != nil {
		prev, err := ihq.path(ctx)
		if err != nil {
			return err
		}
		ihq.sql = prev
	}
	return nil
}

func (ihq *IcoHistoryQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IcoHistory, error) {
	var (
		nodes = []*IcoHistory{}
		_spec = ihq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IcoHistory).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IcoHistory{config: ihq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(ihq.modifiers) > 0 {
		_spec.Modifiers = ihq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ihq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ihq *IcoHistoryQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ihq.querySpec()
	if len(ihq.modifiers) > 0 {
		_spec.Modifiers = ihq.modifiers
	}
	_spec.Node.Columns = ihq.ctx.Fields
	if len(ihq.ctx.Fields) > 0 {
		_spec.Unique = ihq.ctx.Unique != nil && *ihq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ihq.driver, _spec)
}

func (ihq *IcoHistoryQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(icohistory.Table, icohistory.Columns, sqlgraph.NewFieldSpec(icohistory.FieldID, field.TypeString))
	_spec.From = ihq.sql
	if unique := ihq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ihq.path != nil {
		_spec.Unique = true
	}
	if fields := ihq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, icohistory.FieldID)
		for i := range fields {
			if fields[i] != icohistory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ihq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ihq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ihq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ihq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ihq *IcoHistoryQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ihq.driver.Dialect())
	t1 := builder.Table(icohistory.Table)
	columns := ihq.ctx.Fields
	if len(columns) == 0 {
		columns = icohistory.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ihq.sql != nil {
		selector = ihq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ihq.ctx.Unique != nil && *ihq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range ihq.modifiers {
		m(selector)
	}
	for _, p := range ihq.predicates {
		p(selector)
	}
	for _, p := range ihq.order {
		p(selector)
	}
	if offset := ihq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ihq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ihq *IcoHistoryQuery) Modify(modifiers ...func(s *sql.Selector)) *IcoHistorySelect {
	ihq.modifiers = append(ihq.modifiers, modifiers...)
	return ihq.Select()
}

// IcoHistoryGroupBy is the group-by builder for IcoHistory entities.
type IcoHistoryGroupBy struct {
	selector
	build *IcoHistoryQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ihgb *IcoHistoryGroupBy) Aggregate(fns ...AggregateFunc) *IcoHistoryGroupBy {
	ihgb.fns = append(ihgb.fns, fns...)
	return ihgb
}

// Scan applies the selector query and scans the result into the given value.
func (ihgb *IcoHistoryGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ihgb.build.ctx, "GroupBy")
	if err := ihgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IcoHistoryQuery, *IcoHistoryGroupBy](ctx, ihgb.build, ihgb, ihgb.build.inters, v)
}

func (ihgb *IcoHistoryGroupBy) sqlScan(ctx context.Context, root *IcoHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(ihgb.fns))
	for _, fn := range ihgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*ihgb.flds)+len(ihgb.fns))
		for _, f := range *ihgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*ihgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ihgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IcoHistorySelect is the builder for selecting fields of IcoHistory entities.
type IcoHistorySelect struct {
	*IcoHistoryQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ihs *IcoHistorySelect) Aggregate(fns ...AggregateFunc) *IcoHistorySelect {
	ihs.fns = append(ihs.fns, fns...)
	return ihs
}

// Scan applies the selector query and scans the result into the given value.
func (ihs *IcoHistorySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ihs.ctx, "Select")
	if err := ihs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IcoHistoryQuery, *IcoHistorySelect](ctx, ihs.IcoHistoryQuery, ihs, ihs.inters, v)
}

func (ihs *IcoHistorySelect) sqlScan(ctx context.Context, root *IcoHistoryQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ihs.fns))
	for _, fn := range ihs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ihs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ihs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (ihs *IcoHistorySelect) Modify(modifiers ...func(s *sql.Selector)) *IcoHistorySelect {
	ihs.modifiers = append(ihs.modifiers, modifiers...)
	return ihs
}
