// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/indikay/wallet-service/ent/icoround"
	"github.com/rs/xid"
)

// IcoRound is the model entity for the IcoRound schema.
type IcoRound struct {
	config `json:"-"`
	// ID of the ent.
	ID xid.ID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RoundID holds the value of the "round_id" field.
	RoundID int32 `json:"round_id,omitempty"`
	// SubRound holds the value of the "sub_round" field.
	SubRound int32 `json:"sub_round,omitempty"`
	// Price holds the value of the "price" field.
	Price string `json:"price,omitempty"`
	// NumToken holds the value of the "num_token" field.
	NumToken string `json:"num_token,omitempty"`
	// BoughtToken holds the value of the "bought_token" field.
	BoughtToken string `json:"bought_token,omitempty"`
	// StartAt holds the value of the "start_at" field.
	StartAt *time.Time `json:"start_at,omitempty"`
	// EndAt holds the value of the "end_at" field.
	EndAt *time.Time `json:"end_at,omitempty"`
	// IsClose holds the value of the "is_close" field.
	IsClose      bool `json:"is_close,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*IcoRound) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case icoround.FieldIsClose:
			values[i] = new(sql.NullBool)
		case icoround.FieldRoundID, icoround.FieldSubRound:
			values[i] = new(sql.NullInt64)
		case icoround.FieldPrice, icoround.FieldNumToken, icoround.FieldBoughtToken:
			values[i] = new(sql.NullString)
		case icoround.FieldCreatedAt, icoround.FieldUpdatedAt, icoround.FieldStartAt, icoround.FieldEndAt:
			values[i] = new(sql.NullTime)
		case icoround.FieldID:
			values[i] = new(xid.ID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the IcoRound fields.
func (ir *IcoRound) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case icoround.FieldID:
			if value, ok := values[i].(*xid.ID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ir.ID = *value
			}
		case icoround.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ir.CreatedAt = value.Time
			}
		case icoround.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ir.UpdatedAt = value.Time
			}
		case icoround.FieldRoundID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field round_id", values[i])
			} else if value.Valid {
				ir.RoundID = int32(value.Int64)
			}
		case icoround.FieldSubRound:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sub_round", values[i])
			} else if value.Valid {
				ir.SubRound = int32(value.Int64)
			}
		case icoround.FieldPrice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				ir.Price = value.String
			}
		case icoround.FieldNumToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field num_token", values[i])
			} else if value.Valid {
				ir.NumToken = value.String
			}
		case icoround.FieldBoughtToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bought_token", values[i])
			} else if value.Valid {
				ir.BoughtToken = value.String
			}
		case icoround.FieldStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_at", values[i])
			} else if value.Valid {
				ir.StartAt = new(time.Time)
				*ir.StartAt = value.Time
			}
		case icoround.FieldEndAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_at", values[i])
			} else if value.Valid {
				ir.EndAt = new(time.Time)
				*ir.EndAt = value.Time
			}
		case icoround.FieldIsClose:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_close", values[i])
			} else if value.Valid {
				ir.IsClose = value.Bool
			}
		default:
			ir.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the IcoRound.
// This includes values selected through modifiers, order, etc.
func (ir *IcoRound) Value(name string) (ent.Value, error) {
	return ir.selectValues.Get(name)
}

// Update returns a builder for updating this IcoRound.
// Note that you need to call IcoRound.Unwrap() before calling this method if this IcoRound
// was returned from a transaction, and the transaction was committed or rolled back.
func (ir *IcoRound) Update() *IcoRoundUpdateOne {
	return NewIcoRoundClient(ir.config).UpdateOne(ir)
}

// Unwrap unwraps the IcoRound entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ir *IcoRound) Unwrap() *IcoRound {
	_tx, ok := ir.config.driver.(*txDriver)
	if !ok {
		panic("ent: IcoRound is not a transactional entity")
	}
	ir.config.driver = _tx.drv
	return ir
}

// String implements the fmt.Stringer.
func (ir *IcoRound) String() string {
	var builder strings.Builder
	builder.WriteString("IcoRound(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ir.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ir.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ir.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("round_id=")
	builder.WriteString(fmt.Sprintf("%v", ir.RoundID))
	builder.WriteString(", ")
	builder.WriteString("sub_round=")
	builder.WriteString(fmt.Sprintf("%v", ir.SubRound))
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(ir.Price)
	builder.WriteString(", ")
	builder.WriteString("num_token=")
	builder.WriteString(ir.NumToken)
	builder.WriteString(", ")
	builder.WriteString("bought_token=")
	builder.WriteString(ir.BoughtToken)
	builder.WriteString(", ")
	if v := ir.StartAt; v != nil {
		builder.WriteString("start_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := ir.EndAt; v != nil {
		builder.WriteString("end_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("is_close=")
	builder.WriteString(fmt.Sprintf("%v", ir.IsClose))
	builder.WriteByte(')')
	return builder.String()
}

// IcoRounds is a parsable slice of IcoRound.
type IcoRounds []*IcoRound
