// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/indikay/wallet-service/ent/icoround"
	"github.com/indikay/wallet-service/ent/predicate"
	"github.com/rs/xid"
)

// IcoRoundQuery is the builder for querying IcoRound entities.
type IcoRoundQuery struct {
	config
	ctx        *QueryContext
	order      []icoround.OrderOption
	inters     []Interceptor
	predicates []predicate.IcoRound
	modifiers  []func(*sql.Selector)
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IcoRoundQuery builder.
func (irq *IcoRoundQuery) Where(ps ...predicate.IcoRound) *IcoRoundQuery {
	irq.predicates = append(irq.predicates, ps...)
	return irq
}

// Limit the number of records to be returned by this query.
func (irq *IcoRoundQuery) Limit(limit int) *IcoRoundQuery {
	irq.ctx.Limit = &limit
	return irq
}

// Offset to start from.
func (irq *IcoRoundQuery) Offset(offset int) *IcoRoundQuery {
	irq.ctx.Offset = &offset
	return irq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (irq *IcoRoundQuery) Unique(unique bool) *IcoRoundQuery {
	irq.ctx.Unique = &unique
	return irq
}

// Order specifies how the records should be ordered.
func (irq *IcoRoundQuery) Order(o ...icoround.OrderOption) *IcoRoundQuery {
	irq.order = append(irq.order, o...)
	return irq
}

// First returns the first IcoRound entity from the query.
// Returns a *NotFoundError when no IcoRound was found.
func (irq *IcoRoundQuery) First(ctx context.Context) (*IcoRound, error) {
	nodes, err := irq.Limit(1).All(setContextOp(ctx, irq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{icoround.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (irq *IcoRoundQuery) FirstX(ctx context.Context) *IcoRound {
	node, err := irq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IcoRound ID from the query.
// Returns a *NotFoundError when no IcoRound ID was found.
func (irq *IcoRoundQuery) FirstID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = irq.Limit(1).IDs(setContextOp(ctx, irq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{icoround.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (irq *IcoRoundQuery) FirstIDX(ctx context.Context) xid.ID {
	id, err := irq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IcoRound entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IcoRound entity is found.
// Returns a *NotFoundError when no IcoRound entities are found.
func (irq *IcoRoundQuery) Only(ctx context.Context) (*IcoRound, error) {
	nodes, err := irq.Limit(2).All(setContextOp(ctx, irq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{icoround.Label}
	default:
		return nil, &NotSingularError{icoround.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (irq *IcoRoundQuery) OnlyX(ctx context.Context) *IcoRound {
	node, err := irq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IcoRound ID in the query.
// Returns a *NotSingularError when more than one IcoRound ID is found.
// Returns a *NotFoundError when no entities are found.
func (irq *IcoRoundQuery) OnlyID(ctx context.Context) (id xid.ID, err error) {
	var ids []xid.ID
	if ids, err = irq.Limit(2).IDs(setContextOp(ctx, irq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{icoround.Label}
	default:
		err = &NotSingularError{icoround.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (irq *IcoRoundQuery) OnlyIDX(ctx context.Context) xid.ID {
	id, err := irq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IcoRounds.
func (irq *IcoRoundQuery) All(ctx context.Context) ([]*IcoRound, error) {
	ctx = setContextOp(ctx, irq.ctx, "All")
	if err := irq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IcoRound, *IcoRoundQuery]()
	return withInterceptors[[]*IcoRound](ctx, irq, qr, irq.inters)
}

// AllX is like All, but panics if an error occurs.
func (irq *IcoRoundQuery) AllX(ctx context.Context) []*IcoRound {
	nodes, err := irq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IcoRound IDs.
func (irq *IcoRoundQuery) IDs(ctx context.Context) (ids []xid.ID, err error) {
	if irq.ctx.Unique == nil && irq.path != nil {
		irq.Unique(true)
	}
	ctx = setContextOp(ctx, irq.ctx, "IDs")
	if err = irq.Select(icoround.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (irq *IcoRoundQuery) IDsX(ctx context.Context) []xid.ID {
	ids, err := irq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (irq *IcoRoundQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, irq.ctx, "Count")
	if err := irq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, irq, querierCount[*IcoRoundQuery](), irq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (irq *IcoRoundQuery) CountX(ctx context.Context) int {
	count, err := irq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (irq *IcoRoundQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, irq.ctx, "Exist")
	switch _, err := irq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (irq *IcoRoundQuery) ExistX(ctx context.Context) bool {
	exist, err := irq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IcoRoundQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (irq *IcoRoundQuery) Clone() *IcoRoundQuery {
	if irq == nil {
		return nil
	}
	return &IcoRoundQuery{
		config:     irq.config,
		ctx:        irq.ctx.Clone(),
		order:      append([]icoround.OrderOption{}, irq.order...),
		inters:     append([]Interceptor{}, irq.inters...),
		predicates: append([]predicate.IcoRound{}, irq.predicates...),
		// clone intermediate query.
		sql:  irq.sql.Clone(),
		path: irq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IcoRound.Query().
//		GroupBy(icoround.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (irq *IcoRoundQuery) GroupBy(field string, fields ...string) *IcoRoundGroupBy {
	irq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IcoRoundGroupBy{build: irq}
	grbuild.flds = &irq.ctx.Fields
	grbuild.label = icoround.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.IcoRound.Query().
//		Select(icoround.FieldCreatedAt).
//		Scan(ctx, &v)
func (irq *IcoRoundQuery) Select(fields ...string) *IcoRoundSelect {
	irq.ctx.Fields = append(irq.ctx.Fields, fields...)
	sbuild := &IcoRoundSelect{IcoRoundQuery: irq}
	sbuild.label = icoround.Label
	sbuild.flds, sbuild.scan = &irq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IcoRoundSelect configured with the given aggregations.
func (irq *IcoRoundQuery) Aggregate(fns ...AggregateFunc) *IcoRoundSelect {
	return irq.Select().Aggregate(fns...)
}

func (irq *IcoRoundQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range irq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, irq); err != nil {
				return err
			}
		}
	}
	for _, f := range irq.ctx.Fields {
		if !icoround.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if irq.path != nil {
		prev, err := irq.path(ctx)
		if err != nil {
			return err
		}
		irq.sql = prev
	}
	return nil
}

func (irq *IcoRoundQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IcoRound, error) {
	var (
		nodes = []*IcoRound{}
		_spec = irq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IcoRound).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IcoRound{config: irq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	if len(irq.modifiers) > 0 {
		_spec.Modifiers = irq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, irq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (irq *IcoRoundQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := irq.querySpec()
	if len(irq.modifiers) > 0 {
		_spec.Modifiers = irq.modifiers
	}
	_spec.Node.Columns = irq.ctx.Fields
	if len(irq.ctx.Fields) > 0 {
		_spec.Unique = irq.ctx.Unique != nil && *irq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, irq.driver, _spec)
}

func (irq *IcoRoundQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(icoround.Table, icoround.Columns, sqlgraph.NewFieldSpec(icoround.FieldID, field.TypeString))
	_spec.From = irq.sql
	if unique := irq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if irq.path != nil {
		_spec.Unique = true
	}
	if fields := irq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, icoround.FieldID)
		for i := range fields {
			if fields[i] != icoround.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := irq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := irq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := irq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := irq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (irq *IcoRoundQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(irq.driver.Dialect())
	t1 := builder.Table(icoround.Table)
	columns := irq.ctx.Fields
	if len(columns) == 0 {
		columns = icoround.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if irq.sql != nil {
		selector = irq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if irq.ctx.Unique != nil && *irq.ctx.Unique {
		selector.Distinct()
	}
	for _, m := range irq.modifiers {
		m(selector)
	}
	for _, p := range irq.predicates {
		p(selector)
	}
	for _, p := range irq.order {
		p(selector)
	}
	if offset := irq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := irq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// Modify adds a query modifier for attaching custom logic to queries.
func (irq *IcoRoundQuery) Modify(modifiers ...func(s *sql.Selector)) *IcoRoundSelect {
	irq.modifiers = append(irq.modifiers, modifiers...)
	return irq.Select()
}

// IcoRoundGroupBy is the group-by builder for IcoRound entities.
type IcoRoundGroupBy struct {
	selector
	build *IcoRoundQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (irgb *IcoRoundGroupBy) Aggregate(fns ...AggregateFunc) *IcoRoundGroupBy {
	irgb.fns = append(irgb.fns, fns...)
	return irgb
}

// Scan applies the selector query and scans the result into the given value.
func (irgb *IcoRoundGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, irgb.build.ctx, "GroupBy")
	if err := irgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IcoRoundQuery, *IcoRoundGroupBy](ctx, irgb.build, irgb, irgb.build.inters, v)
}

func (irgb *IcoRoundGroupBy) sqlScan(ctx context.Context, root *IcoRoundQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(irgb.fns))
	for _, fn := range irgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*irgb.flds)+len(irgb.fns))
		for _, f := range *irgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*irgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := irgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IcoRoundSelect is the builder for selecting fields of IcoRound entities.
type IcoRoundSelect struct {
	*IcoRoundQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (irs *IcoRoundSelect) Aggregate(fns ...AggregateFunc) *IcoRoundSelect {
	irs.fns = append(irs.fns, fns...)
	return irs
}

// Scan applies the selector query and scans the result into the given value.
func (irs *IcoRoundSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, irs.ctx, "Select")
	if err := irs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IcoRoundQuery, *IcoRoundSelect](ctx, irs.IcoRoundQuery, irs, irs.inters, v)
}

func (irs *IcoRoundSelect) sqlScan(ctx context.Context, root *IcoRoundQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(irs.fns))
	for _, fn := range irs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*irs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := irs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// Modify adds a query modifier for attaching custom logic to queries.
func (irs *IcoRoundSelect) Modify(modifiers ...func(s *sql.Selector)) *IcoRoundSelect {
	irs.modifiers = append(irs.modifiers, modifiers...)
	return irs
}
