// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/indikay/wallet-service/ent/currencyrate"
	"github.com/indikay/wallet-service/ent/ico"
	"github.com/indikay/wallet-service/ent/icocoupon"
	"github.com/indikay/wallet-service/ent/icohistory"
	"github.com/indikay/wallet-service/ent/icoround"
	"github.com/indikay/wallet-service/ent/schema"
	"github.com/indikay/wallet-service/ent/transaction"
	"github.com/indikay/wallet-service/ent/userwallet"
	"github.com/rs/xid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	currencyrateMixin := schema.CurrencyRate{}.Mixin()
	currencyrateMixinFields0 := currencyrateMixin[0].Fields()
	_ = currencyrateMixinFields0
	currencyrateFields := schema.CurrencyRate{}.Fields()
	_ = currencyrateFields
	// currencyrateDescCreatedAt is the schema descriptor for created_at field.
	currencyrateDescCreatedAt := currencyrateMixinFields0[0].Descriptor()
	// currencyrate.DefaultCreatedAt holds the default value on creation for the created_at field.
	currencyrate.DefaultCreatedAt = currencyrateDescCreatedAt.Default.(func() time.Time)
	// currencyrateDescUpdatedAt is the schema descriptor for updated_at field.
	currencyrateDescUpdatedAt := currencyrateMixinFields0[1].Descriptor()
	// currencyrate.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	currencyrate.DefaultUpdatedAt = currencyrateDescUpdatedAt.Default.(func() time.Time)
	// currencyrate.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	currencyrate.UpdateDefaultUpdatedAt = currencyrateDescUpdatedAt.UpdateDefault.(func() time.Time)
	icoMixin := schema.Ico{}.Mixin()
	icoMixinFields0 := icoMixin[0].Fields()
	_ = icoMixinFields0
	icoFields := schema.Ico{}.Fields()
	_ = icoFields
	// icoDescCreatedAt is the schema descriptor for created_at field.
	icoDescCreatedAt := icoMixinFields0[0].Descriptor()
	// ico.DefaultCreatedAt holds the default value on creation for the created_at field.
	ico.DefaultCreatedAt = icoDescCreatedAt.Default.(func() time.Time)
	// icoDescUpdatedAt is the schema descriptor for updated_at field.
	icoDescUpdatedAt := icoMixinFields0[1].Descriptor()
	// ico.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	ico.DefaultUpdatedAt = icoDescUpdatedAt.Default.(func() time.Time)
	// ico.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	ico.UpdateDefaultUpdatedAt = icoDescUpdatedAt.UpdateDefault.(func() time.Time)
	// icoDescID is the schema descriptor for id field.
	icoDescID := icoFields[0].Descriptor()
	// ico.DefaultID holds the default value on creation for the id field.
	ico.DefaultID = icoDescID.Default.(func() xid.ID)
	icocouponMixin := schema.IcoCoupon{}.Mixin()
	icocouponMixinFields0 := icocouponMixin[0].Fields()
	_ = icocouponMixinFields0
	icocouponFields := schema.IcoCoupon{}.Fields()
	_ = icocouponFields
	// icocouponDescCreatedAt is the schema descriptor for created_at field.
	icocouponDescCreatedAt := icocouponMixinFields0[0].Descriptor()
	// icocoupon.DefaultCreatedAt holds the default value on creation for the created_at field.
	icocoupon.DefaultCreatedAt = icocouponDescCreatedAt.Default.(func() time.Time)
	// icocouponDescUpdatedAt is the schema descriptor for updated_at field.
	icocouponDescUpdatedAt := icocouponMixinFields0[1].Descriptor()
	// icocoupon.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	icocoupon.DefaultUpdatedAt = icocouponDescUpdatedAt.Default.(func() time.Time)
	// icocoupon.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	icocoupon.UpdateDefaultUpdatedAt = icocouponDescUpdatedAt.UpdateDefault.(func() time.Time)
	// icocouponDescID is the schema descriptor for id field.
	icocouponDescID := icocouponFields[0].Descriptor()
	// icocoupon.DefaultID holds the default value on creation for the id field.
	icocoupon.DefaultID = icocouponDescID.Default.(func() xid.ID)
	icohistoryMixin := schema.IcoHistory{}.Mixin()
	icohistoryMixinFields0 := icohistoryMixin[0].Fields()
	_ = icohistoryMixinFields0
	icohistoryFields := schema.IcoHistory{}.Fields()
	_ = icohistoryFields
	// icohistoryDescCreatedAt is the schema descriptor for created_at field.
	icohistoryDescCreatedAt := icohistoryMixinFields0[0].Descriptor()
	// icohistory.DefaultCreatedAt holds the default value on creation for the created_at field.
	icohistory.DefaultCreatedAt = icohistoryDescCreatedAt.Default.(func() time.Time)
	// icohistoryDescUpdatedAt is the schema descriptor for updated_at field.
	icohistoryDescUpdatedAt := icohistoryMixinFields0[1].Descriptor()
	// icohistory.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	icohistory.DefaultUpdatedAt = icohistoryDescUpdatedAt.Default.(func() time.Time)
	// icohistory.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	icohistory.UpdateDefaultUpdatedAt = icohistoryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// icohistoryDescID is the schema descriptor for id field.
	icohistoryDescID := icohistoryFields[0].Descriptor()
	// icohistory.DefaultID holds the default value on creation for the id field.
	icohistory.DefaultID = icohistoryDescID.Default.(func() xid.ID)
	icoroundMixin := schema.IcoRound{}.Mixin()
	icoroundMixinFields0 := icoroundMixin[0].Fields()
	_ = icoroundMixinFields0
	icoroundFields := schema.IcoRound{}.Fields()
	_ = icoroundFields
	// icoroundDescCreatedAt is the schema descriptor for created_at field.
	icoroundDescCreatedAt := icoroundMixinFields0[0].Descriptor()
	// icoround.DefaultCreatedAt holds the default value on creation for the created_at field.
	icoround.DefaultCreatedAt = icoroundDescCreatedAt.Default.(func() time.Time)
	// icoroundDescUpdatedAt is the schema descriptor for updated_at field.
	icoroundDescUpdatedAt := icoroundMixinFields0[1].Descriptor()
	// icoround.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	icoround.DefaultUpdatedAt = icoroundDescUpdatedAt.Default.(func() time.Time)
	// icoround.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	icoround.UpdateDefaultUpdatedAt = icoroundDescUpdatedAt.UpdateDefault.(func() time.Time)
	// icoroundDescIsClose is the schema descriptor for is_close field.
	icoroundDescIsClose := icoroundFields[8].Descriptor()
	// icoround.DefaultIsClose holds the default value on creation for the is_close field.
	icoround.DefaultIsClose = icoroundDescIsClose.Default.(bool)
	// icoroundDescID is the schema descriptor for id field.
	icoroundDescID := icoroundFields[0].Descriptor()
	// icoround.DefaultID holds the default value on creation for the id field.
	icoround.DefaultID = icoroundDescID.Default.(func() xid.ID)
	transactionMixin := schema.Transaction{}.Mixin()
	transactionMixinFields0 := transactionMixin[0].Fields()
	_ = transactionMixinFields0
	transactionFields := schema.Transaction{}.Fields()
	_ = transactionFields
	// transactionDescCreatedAt is the schema descriptor for created_at field.
	transactionDescCreatedAt := transactionMixinFields0[0].Descriptor()
	// transaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	transaction.DefaultCreatedAt = transactionDescCreatedAt.Default.(func() time.Time)
	// transactionDescUpdatedAt is the schema descriptor for updated_at field.
	transactionDescUpdatedAt := transactionMixinFields0[1].Descriptor()
	// transaction.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	transaction.DefaultUpdatedAt = transactionDescUpdatedAt.Default.(func() time.Time)
	// transaction.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	transaction.UpdateDefaultUpdatedAt = transactionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// transactionDescID is the schema descriptor for id field.
	transactionDescID := transactionFields[0].Descriptor()
	// transaction.DefaultID holds the default value on creation for the id field.
	transaction.DefaultID = transactionDescID.Default.(func() xid.ID)
	userwalletMixin := schema.UserWallet{}.Mixin()
	userwalletMixinFields0 := userwalletMixin[0].Fields()
	_ = userwalletMixinFields0
	userwalletFields := schema.UserWallet{}.Fields()
	_ = userwalletFields
	// userwalletDescCreatedAt is the schema descriptor for created_at field.
	userwalletDescCreatedAt := userwalletMixinFields0[0].Descriptor()
	// userwallet.DefaultCreatedAt holds the default value on creation for the created_at field.
	userwallet.DefaultCreatedAt = userwalletDescCreatedAt.Default.(func() time.Time)
	// userwalletDescUpdatedAt is the schema descriptor for updated_at field.
	userwalletDescUpdatedAt := userwalletMixinFields0[1].Descriptor()
	// userwallet.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	userwallet.DefaultUpdatedAt = userwalletDescUpdatedAt.Default.(func() time.Time)
	// userwallet.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	userwallet.UpdateDefaultUpdatedAt = userwalletDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userwalletDescID is the schema descriptor for id field.
	userwalletDescID := userwalletFields[0].Descriptor()
	// userwallet.DefaultID holds the default value on creation for the id field.
	userwallet.DefaultID = userwalletDescID.Default.(func() xid.ID)
}
