-- Create "currency_rates" table
CREATE TABLE "currency_rates" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "symbol" character varying NOT NULL, "rate" character varying NOT NULL, "expired_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "currencyrate_symbol" to table: "currency_rates"
CREATE INDEX "currencyrate_symbol" ON "currency_rates" ("symbol");
-- Create "ico_coupons" table
CREATE TABLE "ico_coupons" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "user_id" character varying NOT NULL, "coupon" character varying NOT NULL, "reward" character varying NOT NULL, "cashback" character varying NOT NULL, "deleted_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create index "icocoupon_coupon" to table: "ico_coupons"
CREATE UNIQUE INDEX "icocoupon_coupon" ON "ico_coupons" ("coupon");
-- Create "ico_histories" table
CREATE TABLE "ico_histories" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "round_id" integer NOT NULL, "user_id" character varying NOT NULL, "price" character varying NOT NULL, "num_token" character varying NOT NULL, "sub_round" integer NOT NULL, "type" character varying NULL, PRIMARY KEY ("id"));
-- Create "ico_rounds" table
CREATE TABLE "ico_rounds" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "round_id" integer NOT NULL, "sub_round" integer NOT NULL, "price" character varying NOT NULL, "num_token" character varying NOT NULL, "bought_token" character varying NOT NULL, "start_at" timestamptz NULL, "end_at" timestamptz NULL, "is_close" boolean NOT NULL, PRIMARY KEY ("id"));
-- Create "icos" table
CREATE TABLE "icos" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "round_id" integer NOT NULL, "round_name" character varying NOT NULL, "price" character varying NOT NULL, "num_token" character varying NOT NULL, "num_sub" integer NOT NULL, "price_gap" character varying NOT NULL, "ended_at" timestamptz NULL, PRIMARY KEY ("id"));
-- Create "transactions" table
CREATE TABLE "transactions" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "trans_type" character varying NOT NULL, "source" character varying NOT NULL, "src_symbol" character varying NOT NULL, "src_amount" character varying NOT NULL, "destination" character varying NOT NULL, "dest_symbol" character varying NOT NULL, "dest_amount" character varying NOT NULL, "rate" character varying NOT NULL, "source_service" character varying NOT NULL, "source_id" character varying NOT NULL, "status" character varying NOT NULL, PRIMARY KEY ("id"));
-- Create "user_wallets" table
CREATE TABLE "user_wallets" ("id" character varying NOT NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "user_id" character varying NOT NULL, "type" character varying NOT NULL, "symbol" character varying NOT NULL, "is_active" boolean NOT NULL, "balance" numeric NOT NULL, PRIMARY KEY ("id"));
-- Create index "userwallet_user_id_symbol_type" to table: "user_wallets"
CREATE UNIQUE INDEX "userwallet_user_id_symbol_type" ON "user_wallets" ("user_id", "symbol", "type");
