// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// CurrencyRate is the predicate function for currencyrate builders.
type CurrencyRate func(*sql.Selector)

// Ico is the predicate function for ico builders.
type Ico func(*sql.Selector)

// IcoCoupon is the predicate function for icocoupon builders.
type IcoCoupon func(*sql.Selector)

// IcoHistory is the predicate function for icohistory builders.
type IcoHistory func(*sql.Selector)

// IcoRound is the predicate function for icoround builders.
type IcoRound func(*sql.Selector)

// Transaction is the predicate function for transaction builders.
type Transaction func(*sql.Selector)

// UserWallet is the predicate function for userwallet builders.
type UserWallet func(*sql.Selector)
